export const FETCH_DEDUCTION = "FETCH_DEDUCTION"
export const FETCH_SPECIFIC_DEDUCTION = "FETCH_SPECIFIC_DEDUCTION"
export const RESET_DEDUCTION = "RESET_DEDUCTION"
export const UPDATE_DEDUCTION = "UPDATE_DEDUCTION"