const { hashPassword } = require('../utils/hashPassword');
const { generateAttendance, generateOvertime, generateAttendanceWithLeave, generateLeave } = require('../seed/helper')

exports.seed = async function (knex) {
  await knex('reimbursement').del();
  await knex('deduction').del();
  await knex('bonus').del();
  await knex('payroll').del();
  await knex('allowance').del();
  await knex('allowance_employee').del();
  await knex('leave').del();
  await knex('attendance').del();
  await knex('positions').del();
  await knex('departments').del();
  await knex('overtime').del();
  await knex('employee').del();

  const employeeSeed = await knex.insert([{
    firstname: 'Tai Man',
    lastname: 'Chan',
    address: '47 Yung Shue Wan Main St Lamma Island',
    phone_number: '98244323',
    emergency_contact_person: 'Lili Lai',
    emergency_contact_number: '53423433',
    onboard_date: new Date().toISOString(),
    username: 'admin',
    password: await hashPassword('admin'),
    role: 'admin',
    start_hour: '09:00 AM',
    end_hour: '06:00 PM',
    salary_monthly: 22000.00,
    ot_pay_entitled: true,
    ot_hourly_salary: 80
  }, {
    firstname: 'Keung',
    lastname: 'Chan',
    address: 'Waldorf Gdn Coml Complex Tuen Mun',
    phone_number: '54394333',
    emergency_contact_person: 'Sam Chan',
    emergency_contact_number: '89134131',
    onboard_date: new Date().toISOString(),
    username: 'kc123',
    password: await hashPassword('kc123'),
    role: 'employee',
    start_hour: '09:00 AM',
    end_hour: '06:00 PM',
    salary_monthly: 18000.00
  }, {
    firstname: 'Lisa',
    lastname: 'Chan',
    address: 'Hung Hom',
    phone_number: '54134133',
    emergency_contact_person: 'Samuel Yau',
    emergency_contact_number: '8321221',
    onboard_date: new Date().toISOString(),
    username: 'lc123',
    password: await hashPassword('lc123'),
    role: 'employee',
    start_hour: '10:00 AM',
    end_hour: '09:00 PM',
    salary_monthly: 13000.00
  }]).into('employee').returning(['id']);

  const departmentSeed = await knex('departments').insert([
    { name: "Human Resources", description: "Plan, coordinate, and direct the administrative functions of an organization." },
    { name: "Marketing Promotion", description: "Market research, analysis, and understanding your ideal customer's interests." },
    { name: "Customer Service Support", description: "Providing support to both prospective and existing customers." },
    { name: "Sales", description: "Ensure current customers have the right products and services, identify new markets and customer leads, and pitch prospective customers." },
    { name: "Accounting and Finance", description: "Auditing and analysing financial performance." },
    { name: "Distribution", description: "Spread the product throughout the marketplace such that a large number of people can buy it." },
    { name: "Research and Development", description: "Researching your market and your customer needs and developing new and improved products and services to fit these needs." },
    { name: "Administrative and Management", description: "Provides office support to either an individual or team and is vital for the smooth-running of a business." },
    { name: "Production", description: "Planning and organising production schedules" },
    { name: "Operation", description: "Managing the inner workings of your business so it runs as efficiently as possible." },
    { name: "Information Technology Support", description: "Maintains the computer networks of all types of organisations, providing technical support and ensuring the whole company runs smoothly." },
    { name: "Purchasing", description: "Ensures the supply of goods, production materials and equipment so that a smooth production and sales process can take place." },
    { name: "Legal Department", description: "Provides legal consultation and advice as well as reviewing the rules, contracts and agreements generated by other departments." },
    { name: "Public Relations", description: "Responsible for managing the reputation of a company." },
    { name: "Logistics", description: "Plan, implement, and control the movement and storage of goods, services, or information within a supply chain and between the points of origin and consumption." },
    { name: "Security", description: "Guards patrol and monitor activity at a location or property." }
  ])

  const positionSeed = await knex('positions').insert([
    { post: "Web Developer" },
    { post: "Full Stack Web Developer" },
    { post: "Software Engineer" },
    { post: "Senior Software Engineer" },
    { post: "CTO" },
    { post: "CEO" },
    { post: "Customer Representative" },
    { post: "IT Support" },
    { post: "Accountant" },
    { post: "Business Analytics" },
    { post: "Project Manager" },
    { post: "General Manager" },
    { post: "Customer Service" },
    { post: "Accounting Clerk" },
    { post: "UI designer" },
    { post: "UX researcher" }
  ])

  const allowanceseed = await knex('allowance').insert([
    { name: "Travel Allowance", description: "Covers travel expenses", amount: 500.00, minimum_attendance_required: true, required_attendance_rate: 60.00 },
    { name: "Living Allowance", description: "Covers living expenses", amount: 10000.00, minimum_attendance_required: false, required_attendance_rate: 30.00 },
  ])

  const bonusseed = await knex('bonus').insert([
    { employee_id: employeeSeed[0].id, reason: "being good", amount: 100.00, date: "2021-8-26" }
  ])

  const deductionseed = await knex('deduction').insert([
    { employee_id: employeeSeed[0].id, reason: "This guy broke the office printer", amount: 300.00, date: "2021-8-26" },
  ])

  const attendance = generateAttendance(365, employeeSeed[0].id)
  const attendanceseed = await knex.insert(attendance).into('attendance')
  const overtime = generateOvertime(365, employeeSeed[0].id)
  const overtimeseed = await knex.insert(overtime).into('overtime')

  const attendanceRnd = generateAttendanceWithLeave(60, employeeSeed[1].id, 0.6)
  const atttendancerndseed = await knex.insert(attendanceRnd).into('attendance')
};
